### ISSUE TITLE
How do you actually get it to show?

### ISSUE THREAD

**Issue by ghost** [JonesChi/CastScreen#10]
So I have them connected and the console says it too but I cant see the screen?

Im on linux - rasbian.

I get this error too:

----------------------------------------
Exception happened during processing of request from ('192.168.0.3', 57524)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "cs_receiver.py", line 38, in handle
    p = Popen(['ffplay', '-framerate', '30', '-'], stdin=PIPE, stdout=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
----------------------------------------

**Comment by jmans25** [comment]
you need to install ffmpeg
`$ sudo apt-get install ffmpeg`

Try it with just that first. If it doesn't work,

You might need to install these:
`$ sudo apt-get install libgstreamer0.10-dev libgstreamer0.10-0-dbg libgstreamer0.10-0 gstreamer0.10-tools gstreamer-tools gstreamer0.10-doc gstreamer0.10-x gstreamer1.0-libav`

And install this from this repo:
```
$ sudo add-apt-repository ppa:mc3man/gstffmpeg-keep
$ sudo apt-get update
$ sudo apt-get install gstreamer0.10-ffmpeg
```

FYI: The Python version doesn't work at all with Ubuntu 16.04, the device connects, but nothing shows up 
:( . You have the use the binary. Some devices just don't work (like my Nexus 6) and others do (like my Galaxy Tab A 8.0). 

Sources: 
http://askubuntu.com/questions/380346/how-to-install-gstreamer-1-0-in-ubuntu-12-04
http://askubuntu.com/questions/575869/how-do-i-install-gstreamer0-10-ffmpeg-on-ubuntu-14-10

**Comment by githistory** [comment]
@jmans25 Do I have to run gstreamer in order to get it to show?

**Comment by jmans25** [comment]
@githistory No, it runs automatically if u have everything installed right

**Comment by githistory** [comment]
@jmans25 thanks for the answer. This means that I'm probably missing some settings on my Ubuntu 16.04.
